favicon: null
name: dbleich
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5961317741312087
  brandStrength: 0.8125
  lightness: 0.5625
  brandColors:
    - '#FFFFFF'
    - '#35343A'
    - '#0A0C09'
    - '#8F735E'
    - '#92B072'
  rhythmicContrast: 0.5
typography_spectrum: 0.4731183
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.88802
analytics:
  twitter: null
  google: null
  facebook: null
