name: dbleich
favicon: null
layout_spectrum: 0.8859756502788514
typography_spectrum: 0.20242380374111235
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.932168641127646
  lightness: 0.8901016691233963
  saturation: 0.5961317741312087
  rhythmicContrast: 0.4754741860087961
purpose: []
